import 'package:flc_core/flc_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/router/app_router.dart';
// Generated by `flutter gen-l10n` from lib/l10n/app_en.arb per l10n.yaml —
// does not exist until that command has been run once.
import 'l10n/generated/app_localizations.dart';

class FrontlineClubApp extends ConsumerWidget {
  const FrontlineClubApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);

    return MaterialApp.router(
      title: 'Frontline Club',
      debugShowCheckedModeBanner: false, // briefing §13.7: disable debug banners in release builds
      theme: FlcTheme.light(),
      darkTheme: FlcTheme.dark(),
      themeMode: ThemeMode.system, // overridable from the You tab settings, briefing §9.10 — not yet wired
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales, // en-GB only at launch, briefing §6
      routerConfig: router,
    );
  }
}
