import 'package:flc_core/flc_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'core/preferences/theme_mode_preferences.dart';
import 'core/push/push_service.dart';
import 'core/router/app_router.dart';
import 'core/supabase/supabase_providers.dart';
import 'features/splash/splash_overlay.dart';
// Generated by `flutter gen-l10n` from lib/l10n/app_en.arb per l10n.yaml —
// does not exist until that command has been run once.
import 'l10n/generated/app_localizations.dart';

/// Lets non-widget code (a push notification arriving while the app is open)
/// show a banner without needing a BuildContext.
final GlobalKey<ScaffoldMessengerState> rootMessengerKey = GlobalKey<ScaffoldMessengerState>();

class FrontlineClubApp extends ConsumerStatefulWidget {
  const FrontlineClubApp({super.key});

  @override
  ConsumerState<FrontlineClubApp> createState() => _FrontlineClubAppState();
}

class _FrontlineClubAppState extends ConsumerState<FrontlineClubApp> {
  // Shown once per cold start, over whatever the router renders underneath
  // — see the `builder:` below and SplashOverlay's own doc comment.
  bool _showSplash = true;

  @override
  void initState() {
    super.initState();
    final PushService push = ref.read(pushServiceProvider);
    push.attach(
      onRoute: (String route) => ref.read(appRouterProvider).go(route),
      onForeground: (String title, String body, String? route) {
        rootMessengerKey.currentState
          ?..hideCurrentSnackBar()
          ..showSnackBar(
            SnackBar(
              behavior: SnackBarBehavior.floating,
              duration: const Duration(seconds: 6),
              content: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  if (title.isNotEmpty) Text(title, style: const TextStyle(fontWeight: FontWeight.w700)),
                  if (body.isNotEmpty) Text(body),
                ],
              ),
              action: route == null ? null : SnackBarAction(label: 'View', onPressed: () => ref.read(appRouterProvider).go(route)),
            ),
          );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final router = ref.watch(appRouterProvider);

    // When someone signs in, attach this phone to their account if they've
    // already turned notifications on.
    ref.listen<AsyncValue<AuthState>>(authStateProvider, (previous, next) {
      if (next.valueOrNull?.event == AuthChangeEvent.signedIn) {
        ref.read(pushServiceProvider).syncOnSignIn();
      }
    });

    return MaterialApp.router(
      title: 'Frontline Club',
      debugShowCheckedModeBanner: false, // briefing §13.7: disable debug banners in release builds
      scaffoldMessengerKey: rootMessengerKey,
      theme: FlcTheme.light(),
      darkTheme: FlcTheme.dark(),
      themeMode: ref.watch(themeModeProvider), // You tab → Appearance, briefing §9.10
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales, // en-GB only at launch, briefing §6
      routerConfig: router,
      builder: (BuildContext context, Widget? child) {
        return Stack(
          children: <Widget>[
            if (child != null) child,
            if (_showSplash) SplashOverlay(onFinished: () => setState(() => _showSplash = false)),
          ],
        );
      },
    );
  }
}
