-- Identity: profiles is the one row per user. Membership state lives on it,
-- but member_status is NEVER writable by the user themselves — see the
-- guard trigger in 20260817000009_rls_policies.sql. This file only creates
-- structure; RLS/guards come later so every table exists before policies
-- reference them.

create type user_role as enum ('user', 'staff', 'admin');
create type member_status as enum ('none', 'applied', 'active', 'lapsed', 'suspended');
create type membership_kind as enum ('full', 'honorary', 'lifetime');

create table profiles (
  id                     uuid primary key references auth.users(id) on delete cascade,
  email                  text not null,
  full_name              text,
  display_name           text,
  phone                  text,
  avatar_url             text,

  role                   user_role not null default 'user',

  member_status          member_status not null default 'none',
  membership_kind        membership_kind,
  membership_number      text unique,             -- e.g. 'FLC-01234'
  membership_pin         text,                     -- 4 digits, encrypted at rest (pgsodium/Vault) — see §13
  membership_photo_path  text,                     -- private Storage object path, never a public URL
  membership_started_at  timestamptz,
  membership_expires_at  timestamptz,               -- null for lifetime/honorary
  membership_notes       text,                      -- admin-only, never exposed to the member

  marketing_opt_in       boolean not null default false,
  push_opt_in            boolean not null default false,
  terms_accepted_at      timestamptz,
  privacy_accepted_at    timestamptz,

  deleted_at             timestamptz,               -- soft delete, see the account-deletion flow

  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

comment on column profiles.membership_pin is
  'MUST be encrypted at rest via pgsodium transparent column encryption before production launch (TODO — needs a live project to configure/test pgsodium security labels; stored in plain text in this scaffold). Only ever read inside an Edge Function for the card-render call. Identification tier only — never sufficient alone to authorise a member discount.';
comment on column profiles.membership_photo_path is
  'Points at a private Storage object. Served only via short-lived (15 min) signed URLs generated by an Edge Function — see get-scan-pack / member photo issuing.';

create index profiles_member_status_idx on profiles (member_status);
create index profiles_role_idx on profiles (role) where role <> 'user';

create trigger profiles_set_updated_at
  before update on profiles
  for each row execute function set_updated_at();
